print("") 
print("") 
print("") 
name = input("what is your name?")
print("")
print(f"hello {name}, can I tell you a joke?")
print("") 
input()
print("why should you never give Elsa a balloon?")
input()
print("because she'll let it go")
print("")
print("")
print("")