print("")
print("")
print("")
name = input("What is your name?")
print(f"Hello {name}. Today, we will be doing a short mad lib!")
object = input("Name an object:")
location = input("Name a location:")
adjective = input("Name an adjective:")
adjective2 = input("Name another adjective:")
noun = input("Name any noun:")
adjective3 = input("Name another adjective:")
verb = input("Name a verb that ends in ing:")
print("Now we begin the story:")
print("")
input()
print(f"One day, {name} saw a {object} in {location}.")
input()
print(f"{name} went over to look at it.")
input()
print(f"When {name} went to look it,they noticed it looked {adjective}.")
input()
print(f"{name} also noticed it looked {adjective2}.")
input()
print(f"{name} decided to touch it but then suddenly {noun} came out of the {object}.")
input()
print(f"They were so {adjective3} that {name} was {verb} away.")
input()
print(f"But {name} was curious again, so they decided to go back to the {object} {noun}.")
input()
print(f"But when {name} went back, {noun} was not there anymore. Just the {object} was left.")
input()
print("The end.")
input()
print(f"It was nice meeting you, {name}!")
print("I hoped you enjoyed the mad libs.")