print("")
print("")
print("")
name = input("What is your name?")
print(f"Hello {name}. Today, we will be doing a short mad lib!")
object = input("name an object:")
location = input("name a location:")
adjective = input("name an adjective:")
adjective2 = input("name another adjective:")
noun = input("name any noun:")
adjective3 = input("name another adjective:")
verb = input("name a verb that ends in ing:")
print("now we begin the story:")
print("")
input()
print(f"One day, {name} saw a {object} in {location}.")
input()
print(f"{name} went over to look at it.")
input()
print(f"when {name} went to look it, {name} noticed it looked {adjective}.")
input()
print(f"{name} also noticed it looked {adjective2}")
input()
print(f"{name} decided to touch it but then suddenly {noun} came out of the {object}")
input()
print(f"{name} was so {adjective3} that {name} was {verb} away")
input()
print(f"but {name} was curious again, so she decided to go back to the {object} {noun}")
input()
print(f"but when {name} went back, {noun} was not there anymore. just the {object} was left")
input()
print("the end")
input()
print(f"it was nice meeting you, {name}!")
print("I hoped you enjoyed the mad libs")