print("")
print("")
print("")
name = input("What is your name?")
print(f"Hello {name}. Today, we will be doing a short mad lib!")
object = input("name an object:")
location = input("name a location:")
verb = input("name a verb:")
adjective = input("name an adjective:")
print("now we begin the story:")
print(f"One day, {name} saw a {object} in {location}.")
print(f"{name} went over to {verb} at it.")
print(f"when {name} went to {verb} it, {name} noticed it looked {adjective}.")